name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
      - "download-artifact"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "CI.yml"
          repo: "falcosecurity/falco"
          run_id: 5764491712
          name: falco-0.35.1-56+f3db07b-wasm.tar.gz

      - name: Extract artifact
        run: |
          tar -xvf falco-0.35.1-56+f3db07b-wasm.tar.gz
          mv falco-0.35.1-56+f3db07b-wasm/usr/bin/falco.wasm ./public
          mv falco-0.35.1-56+f3db07b-wasm/usr/bin/falco.js  ./src/Hooks/

      - name: Remove Unwanted Artifacts
        run: rm -rf falco-0.35.1-56+f3db07b-wasm.tar.gz falco-0.35.1-56+f3db07b-wasm

      - name: Fix falco.js export
        run: |
          sudo apt install -y perl
          perl -i -p0e  "s/(if \(typeof exports === 'object' && typeof module === 'object'\))[\s\S]*/export default Module;/g" ./src/Hooks/falco.js

      - name: Test
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:5173
          start: npx vite --host

      - name: Install and build
        run: npm install && npm run build && cd dist && rm -rf monacoeditorwork

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
